name: pro_flutter
description: A new Flutter project.

version: 1.0.2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_riverpod: ^0.14.0+3
  toast: any
  flare_flutter: ^2.0.6
  smart_flare: ^0.2.9+1
  retrofit: ^2.0.1
  logger: ^1.1.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  json_annotation: ^4.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.7
  freezed_annotation: ^0.14.2
  sp_util: ^2.0.3
  pull_to_refresh: ^2.0.0
  lottie: ^1.1.0
  transparent_image: ^2.0.0
  extended_image: ^4.1.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.1
  build_runner: ^2.1.2
  json_serializable: ^4.1.4
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/home.png
    - assets/images/Listview.png
    - assets/images/history.png
    - assets/images/wode.png
    - assets/images/off_home.png
    - assets/images/off_Listview.png
    - assets/images/off_history.png
    - assets/images/off_wode.png
    - assets/images/icon.png
    - assets/images/noComment.png
    - assets/images/icon_accountAbout.png
    - assets/images/icon_accountNumber.png
    - assets/images/icon_accountPassword.png
    - assets/images/animationImage.gif
    - assets/Teddy.flr
    - assets/button-animation.flr
    - assets/slideout-menu.flr
    - assets/json/empty.json
    - assets/json/disconnect.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/loadingYellow.json
    - assets/json/loading2.json
    - assets/json/error2.json
    - assets/json/empty2.json
    - assets/json/empty3.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
  - family: FZDaLTJ
    fonts:
      - asset: assets/fonts/fzDaLTJ.ttf
  - family: FZFWQingYinTiJWL
    fonts:
      - asset: assets/fonts/fzFWQingYinTiJWL.ttf
  - family: FZFWZhuZiAYuanJWM
    fonts:
      - asset: assets/fonts/fzFWZhuZiAYuanJWM.ttf
  - family: SourceHanSans
    fonts:
      - asset: assets/fonts/sourceHanSansMedium.ttc
  - family: Rzzyt
    fonts:
      - asset: assets/fonts/rzzyt.ttf
  - family: IconFont
    fonts:
        - asset: assets/fonts/iconfont.ttf
